// --- START OF FILE geminiService.ts (MODIFIED SNIPPET) ---

// REMOVE: import { GoogleGenAI, Type, ... } from "@google/genai";
// REMOVE: if (!process.env.API_KEY) { ... }
// REMOVE: const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
import { MidiNote } from '../types';

// ... all other functions (Midi, Chat, etc.) must be refactored the same way! ...

// Refactored generateImage function to use the secure backend
export const generateImage = async (prompt: string): Promise<string> => {
    try {
        const response = await fetch('/api/generate-image', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ prompt }),
        });

        if (!response.ok) {
            const error = await response.json();
            throw new Error(error.error || 'Failed to generate image via secure API.');
        }
        
        // The backend now returns the Base64 string in 'imageBytes'
        const data = await response.json();

        // data.imageBytes is the raw Base64 string of the JPEG image
        if (data.imageBytes) {
            return data.imageBytes;
        } else {
            throw new Error("No image was generated by the API.");
        }
    } catch (error) {
        console.error('Error generating image:', error);
        throw new Error(error instanceof Error ? error.message : 'An unknown error occurred during image generation.');
    }
};

// ... continue refactoring all other functions (Midi, Video, Chat, Speech) ...